servers:
  web:
    hosts:
      - 5.161.188.126
    proxy: false


proxy: false

registry:
  server: ghcr.io
  username: omarshaarawi
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - SWID
    - LEAGUE_ID
    - ESPN_S2
    - YEAR
    - TELEGRAM_TOKEN
    - CHAT_ID
    - KAMAL_REGISTRY_PASSWORD

